/**
 * NIM-ACh — Site Data
 * Centralised data store. Edit here to update all sections.
 * In a production build, replace with API calls to a CMS.
 */

const NIMACH_DATA = {

  /* ─── People ─── */
  people: [
    {
      id:            'cristian-nunez',
      initials:      'CN',
      name:          'Dr. Cristian Núñez Espinosa',
      role:          'Investigador Principal · CADI-UMAG',
      role_category: 'pi',
      avatar:        'av1',
      ringColor:     '#3b7abf',
      bio:           'Doctor en Ciencias de la Salud. Especialista en neurofisiología y regulación autonómica cardíaca. Lidera el laboratorio NIM-ACh y proyectos FONDECYT sobre el eje cerebro-corazón en contextos extremos patagónicos. Académico de la Escuela de Medicina de la UMAG.',
      chips:         ['FONDECYT', 'Neurofisiología', 'HRV'],
      links:         { researchgate: '#', orcid: '#', scholar: '#' },
    },
    {
      id:            'matias-castillo',
      initials:      'MC',
      name:          'Matías Castillo-Aguilar',
      role:          'Investigador · Desarrollador de herramientas',
      role_category: 'researcher',
      avatar:        'av2',
      ringColor:     '#e87040',
      bio:           'Kinesiólogo e investigador con especialización en análisis de señales fisiológicas y desarrollo de software científico. Creador del HRV Analyzer para Polar H10. Candidato a Doctor en Ciencias de la Salud.',
      chips:         ['HRV', 'App Dev', 'Polar H10'],
      links:         { github: '#', orcid: '#' },
    },
    {
      id:            'tiare-ibinarriaga',
      initials:      'TI',
      name:          'Tiare Ibinarriaga',
      role:          'Investigadora doctoral · UDD 2025',
      role_category: 'doctoral',
      avatar:        'av3',
      ringColor:     '#1db884',
      bio:           'Psicóloga, doctoranda en Psicología Clínica en la Universidad del Desarrollo. Investiga la relación entre regulación emocional, psicopatología y el sistema nervioso autónomo en etapas del desarrollo.',
      chips:         ['PhD', 'Psicopatología', 'Desarrollo'],
      links:         { researchgate: '#' },
    },
    {
      id:            'leyla-vasquez',
      initials:      'LV',
      name:          'Leyla Vásquez',
      role:          'Investigadora asociada',
      role_category: 'researcher',
      avatar:        'av4',
      ringColor:     '#7b52d4',
      bio:           'Terapeuta ocupacional con enfoque en envejecimiento saludable e intervenciones no farmacológicas. Lidera los protocolos de mindfulness en adultos mayores de la Región de Magallanes.',
      chips:         ['Envejecimiento', 'Mindfulness'],
      links:         { researchgate: '#' },
    },
    {
      id:            'jonathan-perez',
      initials:      'JP',
      name:          'Jonathan Pérez',
      role:          'Investigador asociado',
      role_category: 'researcher',
      avatar:        'av5',
      ringColor:     '#d4903a',
      bio:           'Profesor de Educación Física, Magíster en Ciencias de la Actividad Física. Especialista en fisiología del ejercicio y respuesta autonómica al entrenamiento en condiciones de frío extremo.',
      chips:         ['Ejercicio', 'Fisiología'],
      links:         { researchgate: '#' },
    },
    {
      id:            'pedro-medina',
      initials:      'PM',
      name:          'Pedro Medina',
      role:          'Investigador asociado',
      role_category: 'researcher',
      avatar:        'av6',
      ringColor:     '#3baabf',
      bio:           'Kinesiólogo especializado en fisiología del frío y medicina del deporte. Coordina los protocolos de inmersión en aguas gélidas del proyecto FONDECYT Regular vigente.',
      chips:         ['Autonomic', 'Cold'],
      links:         { researchgate: '#' },
    },
  ],

  /* ─── Publications ─── */
  publications: [
    {
      id:      'pub-2025-hrv-cold',
      year:    2025,
      title:   'Cardiac autonomic regulation in cold-water exposure: HRV analysis in Patagonian open-water swimmers',
      authors: 'Núñez C., Castillo-Aguilar M., Medina P. et al.',
      journal: 'Journal of Physiology',
      quartile:'Q1',
      doi:     '10.XXXX/jphysiol.2025.XXXXX',
      openalex_id: '',
      topics:  ['hrv', 'cold', 'exercise'],
    },
    {
      id:      'pub-2024-mindfulness',
      year:    2024,
      title:   'Mindfulness-based intervention effects on autonomic regulation and cognitive function in older adults',
      authors: 'Núñez C., Ibinarriaga T., Vásquez L. et al.',
      journal: 'Frontiers in Aging Neuroscience',
      quartile:'Q1',
      doi:     '10.XXXX/fnagi.2024.XXXXX',
      openalex_id: '',
      topics:  ['mindfulness', 'aging', 'cognition'],
    },
    {
      id:      'pub-2024-seasonal',
      year:    2024,
      title:   'Seasonal light variation and autonomic nervous system activity in high-latitude elderly populations',
      authors: 'Núñez C., Pérez J. et al.',
      journal: 'Chronobiology International',
      quartile:'Q2',
      doi:     '10.XXXX/chrono.2024.XXXXX',
      openalex_id: '',
      topics:  ['circadian', 'aging', 'light'],
    },
    {
      id:      'pub-2023-review',
      year:    2023,
      title:   'Heart rate variability as a biomarker of neuromodulation in extreme environments: a systematic review',
      authors: 'Castillo-Aguilar M., Núñez C. et al.',
      journal: 'Autonomic Neuroscience',
      quartile:'Q2',
      doi:     '10.XXXX/autneu.2023.XXXXX',
      openalex_id: '',
      topics:  ['hrv', 'extreme', 'review'],
    },
  ],

  /* ─── Projects ─── */
  projects: [
    {
      id:      'proj-fondecyt-regular-2025',
      status:  'active',
      agency:  'ANID · FONDECYT Regular',
      code:    'Nº 1XXXXXX',
      title:   'Regulación autonómica cardíaca en condiciones de frío extremo: estudio en nadadores de aguas gélidas de Magallanes',
      pi:      'Dr. Cristian Núñez Espinosa',
      period:  '2025–2028',
      amount:  '$105M CLP',
      type:    'Regular',
      progress: 25,
      barColor: 'pf-teal',
      tags:    ['HRV', 'Cold water', 'Patagonia', 'Autonomic'],
    },
    {
      id:      'proj-mediantar-2024',
      status:  'active',
      agency:  'UE · ERASMUS+',
      code:    'MEDIANTAR 2024–2028',
      title:   'Mediterranean and Antarctic Research Network: ambientes extremos y ejercicio físico en contextos internacionales',
      pi:      'Colaborador: Dr. Cristian Núñez Espinosa',
      period:  '2024–2028',
      amount:  'Internacional',
      type:    'Internacional',
      progress: 40,
      barColor: 'pf-blue',
      tags:    ['International', 'Brazil', 'Exercise', 'Extreme env.'],
    },
    {
      id:      'proj-fondecyt-ini-2022',
      status:  'complete',
      agency:  'ANID · FONDECYT Iniciación',
      code:    'Nº 11XXXXX',
      title:   'Efectos de la luz estacional en la regulación autonómica de personas mayores residentes en la Región de Magallanes',
      pi:      'Dr. Cristian Núñez Espinosa',
      period:  '2022–2024',
      amount:  '$55M CLP',
      type:    'Iniciación',
      progress: 100,
      barColor: 'pf-coral',
      tags:    ['Seasonal light', 'Elderly', 'Circadian'],
    },
    {
      id:      'proj-ries-lac',
      status:  'active',
      agency:  'ANID · REDES',
      code:    'RIES-LAC',
      title:   'Red Interuniversitaria de Envejecimiento Saludable para América Latina y el Caribe — participación NIM-ACh',
      pi:      'Dr. Cristian Núñez Espinosa',
      period:  '2024–2026',
      amount:  'Red',
      type:    'Red ANID',
      progress: 60,
      barColor: 'pf-purple',
      tags:    ['Aging', 'LATAM', 'Network'],
    },
  ],

  /* ─── News ─── */
  news: [
    { date:'Dic 2025', hot:true,  text:'Matías Castillo-Aguilar lanza app web para análisis de VFC con bandas Polar H10.',                                             tag:'Herramienta open-source', link:'https://deft-torte-3c1940.netlify.app/' },
    { date:'Jun 2025', hot:true,  text:'Primer Seminario "Mentes del Fin del Mundo" — con estudiantes de toda la Región de Magallanes.',                               tag:'Divulgación' },
    { date:'Ene 2025', hot:true,  text:'Dr. Cristian Núñez adjudica FONDECYT Regular 2025.',                                                                          tag:'Financiamiento' },
    { date:'Nov 2024', hot:false, text:'Tiare Ibinarriaga aceptada en programa de Doctorado — UDD 2025.',                                                             tag:'Formación' },
    { date:'Jun 2024', hot:false, text:'Inicio de mediciones en nadadores de aguas gélidas de Magallanes.',                                                           tag:'Terreno' },
    { date:'May 2024', hot:false, text:'Vínculo con Universidad de Salvador de Bahía en el marco de MEDIANTAR.',                                                      tag:'Internacional' },
    { date:'Ene 2024', hot:false, text:'Colaboraciones con RIES-LAC — Red Interuniversitaria de Envejecimiento Saludable.',                                           tag:'Colaboración' },
    { date:'May 2023', hot:false, text:'Inicio de proyecto FONDECYT Iniciación con evaluación de deportistas y mindfulness en personas mayores.',                     tag:'Investigación' },
  ],

  /* ─── Research lines ─── */
  research: [
    {
      id:    'neuromodulation',
      icon:  '🧠',
      color: 'rc-blue',
      ic:    'ic-blue',
      title: 'Neuromodulación y variabilidad de frecuencia cardíaca',
      desc:  'Evaluación de la VFC como marcador del control autonómico bajo diversas condiciones fisiológicas, psicológicas y ambientales.',
      tags:  ['HRV', 'Autonomic NS', 'Polar H10', 'Wearables'],
    },
    {
      id:    'extreme-environments',
      icon:  '🏔️',
      color: 'rc-coral',
      ic:    'ic-coral',
      title: 'Ambientes extremos y estrés fisiológico',
      desc:  'Respuesta del eje cerebro-corazón al frío extremo, altitud, inmersión en aguas gélidas y ejercicio intenso en la Patagonia.',
      tags:  ['Cold exposure', 'Exercise', 'Patagonia', 'Open water'],
    },
    {
      id:    'aging-mindfulness',
      icon:  '🌿',
      color: 'rc-teal',
      ic:    'ic-teal',
      title: 'Mindfulness y envejecimiento saludable',
      desc:  'Efecto de intervenciones de mindfulness sobre el deterioro cognitivo y la regulación autonómica en adultos mayores de Magallanes.',
      tags:  ['Aging', 'Mindfulness', 'Cognition', 'RIES-LAC'],
    },
  ],

  /* ─── Collaborators ─── */
  collaborators: [
    { name:'MEDIANTAR',        url:'#' },
    { name:'RIES-LAC',         url:'#' },
    { name:'CIES',             url:'#' },
    { name:'HABITAT',          url:'#' },
    { name:'U. Salvador Bahía',url:'#' },
    { name:'FONDECYT',         url:'#' },
  ],
  
  globePoints: [
    { lat:-53.16, lon:-70.91, label:'Punta Arenas — NIM-ACh', color:'#e87040', r:1.0, home:true  },
    { lat:-33.45, lon:-70.66, label:'Santiago',                color:'#7fb3e8', r:0.6, home:false },
    { lat:-12.97, lon:-38.50, label:'Salvador de Bahía · MEDIANTAR', color:'#7fb3e8', r:0.7, home:false },
    { lat: 19.43, lon:-99.13, label:'Ciudad de México · RIES-LAC',   color:'#7fb3e8', r:0.6, home:false },
    { lat: 40.42, lon: -3.70, label:'Madrid · ERASMUS+',       color:'#1db884', r:0.7, home:false },
    { lat: 48.86, lon:  2.35, label:'París',                   color:'#7fb3e8', r:0.5, home:false },
    { lat: 41.90, lon: 12.49, label:'Roma · MEDIANTAR',        color:'#7fb3e8', r:0.6, home:false },
    { lat:-34.90, lon:-56.17, label:'Montevideo · RIES-LAC',   color:'#b07fd4', r:0.5, home:false },
  ],

  /* ─── Gallery items ─── */
  gallery: [
    { id:'g1', bg:'gi-1', span:true,  title:'Mediciones de VFC en laboratorio',           sub:'CADI-UMAG · 2024' },
    { id:'g2', bg:'gi-2', span:false, title:'Terreno en Patagonia',                       sub:'Nadadores aguas gélidas · Jun 2024' },
    { id:'g3', bg:'gi-3', span:false, title:'Seminario Mentes del Fin del Mundo',         sub:'Punta Arenas · Jun 2025' },
    { id:'g4', bg:'gi-4', span:false, title:'Colaboración MEDIANTAR',                     sub:'Brasil · 2024' },
    { id:'g5', bg:'gi-5', span:false, title:'CIES Jornadas Talca',                        sub:'Congreso · Sep 2023' },
    { id:'g6', bg:'gi-6', span:false, title:'Mediciones mindfulness adultos mayores',     sub:'UMAG · 2023' },
  ],
  
  /* ─── Tools ─── */
  tools: [
    {
      id:       'hrv-analyzer',
      icon:     '💓',
      status:   'active',
      version:  'v2.0',
      title:    'HRV Analyzer — Polar H10 Web App',
      desc:     'Aplicación web para análisis de variabilidad de frecuencia cardíaca en tiempo real usando bandas Polar H10 vía Web Bluetooth. Sin instalación, sin cuenta, sin costo.',
      features: [
        'Métricas en dominio tiempo (SDNN, RMSSD, pNN50)',
        'Análisis frecuencial (LF, HF, LF/HF)',
        'Poincaré plot en tiempo real',
        'Exportación CSV / JSON',
        'Compatible con Polar H10 y H9',
      ],
      tags:     ['Web Bluetooth', 'JavaScript', 'HRV', 'Polar H10', 'Open Source'],
      author:   'matias-castillo',
      url:      'https://deft-torte-3c1940.netlify.app/',
      github:   '#',
      docs:     '#',
    },
    {
      id:       'nim-stats',
      icon:     '📊',
      status:   'dev',
      version:  null,
      title:    'NIM-Stats — Pipeline estadístico HRV',
      desc:     'CLI en Python para procesamiento batch de archivos RR. Genera reportes automáticos en PDF con visualizaciones estandarizadas y estadísticas descriptivas.',
      features: [
        'Procesamiento batch de archivos .rr y .csv',
        'Reporte PDF automatizado',
        'Gráficos Poincaré y frecuencial',
        'Compatible con Polar, Garmin y Kubios',
      ],
      tags:     ['Python', 'CLI', 'Batch', 'PDF'],
      author:   'matias-castillo',
      url:      null,
      github:   '#',
      docs:     null,
    },
    {
      id:       'nim-annotator',
      icon:     '🗂️',
      status:   'planned',
      version:  null,
      title:    'NIM-Annotator — Etiquetado de artefactos',
      desc:     'Interfaz visual para revisar y limpiar series RR, con detección automática de ectópicos y exportación de segmentos anotados con metadatos.',
      features: [
        'Detección automática de latidos ectópicos',
        'Edición manual de artefactos',
        'Exportación de segmentos con metadatos',
        'Integración con NIM-Stats',
      ],
      tags:     ['React', 'Annotation', 'QC', 'TypeScript'],
      author:   null,
      url:      null,
      github:   null,
      docs:     null,
    },
  ],

  /* ─── News / Timeline ─── */
  news: [
    {
      date: 'Dic 2025',
      html: 'Matías Castillo-Aguilar lanza <a href="https://deft-torte-3c1940.netlify.app/" style="color:var(--c-coral)">app web</a> para análisis de VFC con bandas Polar H10.',
      tag:  'Herramienta open-source',
      hot:  true,
    },
    {
      date: 'Jun 2025',
      html: 'Primer Seminario "Mentes del Fin del Mundo" — gran convocatoria regional en Punta Arenas.',
      tag:  'Divulgación',
      hot:  true,
    },
    {
      date: 'Ene 2025',
      html: 'Dr. Núñez inicia trabajo de campo del FONDECYT Regular con nadadores de aguas gélidas de Magallanes.',
      tag:  'Investigación',
      hot:  true,
    },
    {
      date: 'Oct 2024',
      html: 'NIM-ACh presentó 3 trabajos en el congreso CIES 2024 en Talca. Dos menciones de honor.',
      tag:  'Congreso',
      hot:  false,
    },
    {
      date: 'Ago 2024',
      html: 'Inicio oficial de colaboración MEDIANTAR (ERASMUS+) con universidades de Brasil, España e Italia.',
      tag:  'Colaboración internacional',
      hot:  false,
    },
    {
      date: 'Mar 2024',
      html: 'Publicación aceptada en <em>Frontiers in Aging Neuroscience</em>: efectos del mindfulness en adultos mayores.',
      tag:  'Publicación',
      hot:  false,
    },
    {
      date: 'Dic 2023',
      html: 'NIM-ACh se incorpora a la Red RIES-LAC de envejecimiento saludable en América Latina.',
      tag:  'Red científica',
      hot:  false,
    },
  ],
};

window.NIMACH_DATA = NIMACH_DATA;
