/**
 * NIM-ACh — Site Data
 * Centralised data store. Edit here to update all sections.
 * In a production build, replace with API calls to a CMS.
 */

const NIMACH_DATA = {
  
  // ADD before  people: [
  people_categories: [
    { key: 'pi',            label: 'Investigación Principal'   },
    { key: 'researcher',    label: 'Investigadores'            },
    { key: 'undergrad',     label: 'Estudiante de Pregrado'    },
    { key: 'posgrad',       label: 'Estudiante de Posgrado'    },
    { key: 'clinician',     label: 'Colaboradores Clínicos'    },
    { key: 'collaborator',  label: 'Colaboradores Externos'    },
    { key: 'staff',         label: 'Gestión y Apoyo'           },
  ],

  /* ─── People ─── */
  people: [
    {
      id:            'cristian-nunez',
      active:        true,
      initials:      'CN',
      name:          'Cristian Núñez Espinosa',
      role:          'Investigador Principal · CADI-UMAG',
      role_category: ['pi'],
      avatar:        'av1',
      photo:         'assets/images/team/cris-nunez.jpg', 
      featured_home: true,
      ringColor:     '#3b7abf',
      bio:           'Doctor en Fisiología. Especialista en neurofisiología y regulación autonómica cardíaca. Lidera el laboratorio NIM-ACh y proyectos FONDECYT sobre el eje cerebro-corazón en contextos extremos patagónicos. Académico de la Escuela de Medicina de la UMAG.',
      chips:         ['FONDECYT', 'Neurofisiología', 'HRV'],
      links:         { researchgate: '#', orcid: '#', scholar: '#' },
    },
    {
      id:            'matias-castillo',
      active:        true,
      initials:      'MCA',
      name:          'Matías Castillo-Aguilar',
      role:          'Investigador · Desarrollador de herramientas',
      role_category: ['researcher'],
      avatar:        'av2',
      photo:         'assets/images/team/matias-castillo.jpeg', 
      featured_home: true,
      ringColor:     '#e87040',
      bio:           'Kinesiólogo e investigador con especialización en análisis de señales fisiológicas y desarrollo de software científico. Creador del HRV Analyzer para Polar H10.',
      chips:         ['HRV', 'App Dev', 'Polar H10'],
      links:         { github: '#', orcid: '#' },
    },
    {
      id:            'javiera-gonzalez',
      active:        true,
      initials:      'JG',
      name:          'Javiera Gonzalez',
      role:          'Coordinadora general',
      role_category: ["staff"],
      featured_home: true,
      avatar:        'av6',
      photo:         'assets/images/team/javiera-gonzalez.jpg', 
      ringColor:     '#3baabf',
      bio:           'Kinesióloga y coordinadora general del equipo. Contribuye a gestionar evaluaciones, insumos y reuniones dentro del grupo.',
      chips:         ['gestion'],
      links:         { researchgate: '#' },
    },
    {
      id:            'tiare-ibinarriaga',
      active:        false,
      initials:      'TI',
      name:          'Tiare Ibinarriaga',
      role:          'Investigadora doctoral · UDD 2025',
      role_category: ['posgrad'],
      avatar:        'av3',
      photo:         'assets/images/team/tiare-ibinarriaga.jpg', 
      featured_home: false,
      ringColor:     '#1db884',
      bio:           'Psicóloga, doctoranda en Psicología Clínica en la Universidad del Desarrollo. Investiga la relación entre regulación emocional, psicopatología y el sistema nervioso autónomo en etapas del desarrollo.',
      chips:         ['PhD', 'Psicopatología', 'Desarrollo'],
      links:         { researchgate: '#' },
    },
    {
      id:            'leyla-huirimilla',
      active:        true,
      initials:      'LV',
      name:          'Leyla Huirimilla',
      role:          'Investigadora asociada',
      role_category: ['posgrad', 'researcher'],
      avatar:        'av4',
      photo:         'assets/images/team/leyla-huirimilla.jpg', 
      featured_home: false,
      ringColor:     '#7b52d4',
      bio:           'Psicóloga clínica, Magíster en Psicobiología del Desarrollo. Estudiante de Doctorado',
      chips:         ['Envejecimiento', 'Mindfulness'],
      links:         { researchgate: '#' },
    },
    {
      id:            'jonathan-luhr',
      active:        true,
      initials:      'JL',
      name:          'Jonathan Lühr',
      role:          'Investigador asociado',
      role_category: ['posgrad', 'researcher'],
      avatar:        'av5',
      photo:         'assets/images/team/jonathan.jpg', 
      featured_home: false,
      ringColor:     '#d4903a',
      bio:           'Psicólogo Clínico',
      chips:         ['Ejercicio', 'Fisiología'],
      links:         { researchgate: '#' },
    },
  ],

  /* ─── Publications ─── */
  publications: [],
  
  /* ─── Alumni ─── */
  alumni: [
    {
      id:        'sofia-reyes',
      initials:  'SR',
      name:      'Dra. Sofía Reyes',
      role:      'Investigadora Postdoctoral',
      period:    '2021–2023',
      avatar:    'av3',   // reutiliza colores de avatar existentes
      ringColor: '#7b52d4',
      bio:       'Desarrolló su postdoctorado en el grupo trabajando en regulación autonómica y estrés oxidativo. Actualmente en la Universidad de Concepción.',
      chips:     ['Postdoc', 'Estrés oxidativo', 'HRV'],
      links:     { researchgate: '#', orcid: '#' },
      currentPosition: 'Universidad de Concepción',
    },
    {
      id:        'marco-soto',
      initials:  'MS',
      name:      'Marco Soto',
      role:      'Tesista de pregrado',
      period:    '2022–2023',
      avatar:    'av5',
      ringColor: '#3baabf',
      bio:       'Realizó su tesis de kinesiología sobre VFC en nadadores de aguas abiertas. Actualmente kinesiólogo clínico en Punta Arenas.',
      chips:     ['Pregrado', 'Kinesiología', 'HRV'],
      links:     { researchgate: '#' },
      currentPosition: 'Clínica Magallanes',
    },
  ],

  /* ─── NIMAChinos (mascotas del equipo) ─── */
  pets: [
    {
      id:       'pet-canela',
      name:     'Canela',
      species:  'Perra',
      breed:    'Mestiza rescatada',
      emoji:    '🐕',
      owner:    'cristian-nunez',   // id del dueño en people[]
      bio:      'La primera NIMAChina oficial. Experta en HRV de reposo y en interrumpir reuniones de Zoom en los momentos más inoportunos.',
      chips:    ['Jefa de seguridad', 'HRV en reposo'],
      joined:   '2020',
    },
    {
      id:       'pet-bits',
      name:     'Bits',
      species:  'Gato',
      breed:    'Scottish Fold naranja',
      emoji:    '🐱',
      owner:    'matias-castillo',
      bio:      'Supervisor técnico del desarrollo del HRV Analyzer. Verifica cada commit con su mirada escéptica y ocasionalmente camina sobre el teclado para contribuir.',
      chips:    ['Code review', 'QA testing'],
      joined:   '2022',
    },
    {
      id:       'pet-darwin',
      name:     'Darwin',
      species:  'Perro',
      breed:    'Labrador negro',
      emoji:    '🐶',
      owner:    'leyla-vasquez',
      bio:      'Participa activamente en los protocolos de mindfulness como co-terapeuta no certificado. Su presencia reduce el cortisol en un 40% (no revisado por pares).',
      chips:    ['Mindfulness', 'Terapia asistida'],
      joined:   '2021',
    },
  ],

  /* ─── Projects ─── */
  projects: [
    {
      id:      'proj-fondecyt-regular-2025',
      status:  'active',
      agency:  'ANID · FONDECYT Regular',
      code:    'Nº 1XXXXXX',
      title:   'Regulación autonómica cardíaca en condiciones de frío extremo: estudio en nadadores de aguas gélidas de Magallanes',
      pi:      'Dr. Cristian Núñez Espinosa',
      period:  '2025–2028',
      amount:  '$105M CLP',
      type:    'Regular',
      progress: 25,
      barColor: 'pf-teal',
      tags:    ['HRV', 'Cold water', 'Patagonia', 'Autonomic'],
    },
    {
      id:      'proj-mediantar-2024',
      status:  'active',
      agency:  'UE · ERASMUS+',
      code:    'MEDIANTAR 2024–2028',
      title:   'Mediterranean and Antarctic Research Network: ambientes extremos y ejercicio físico en contextos internacionales',
      pi:      'Colaborador: Dr. Cristian Núñez Espinosa',
      period:  '2024–2028',
      amount:  'Internacional',
      type:    'Internacional',
      progress: 40,
      barColor: 'pf-blue',
      tags:    ['International', 'Brazil', 'Exercise', 'Extreme env.'],
    },
    {
      id:      'proj-fondecyt-ini-2022',
      status:  'complete',
      agency:  'ANID · FONDECYT Iniciación',
      code:    'Nº 11XXXXX',
      title:   'Efectos de la luz estacional en la regulación autonómica de personas mayores residentes en la Región de Magallanes',
      pi:      'Dr. Cristian Núñez Espinosa',
      period:  '2022–2024',
      amount:  '$55M CLP',
      type:    'Iniciación',
      progress: 100,
      barColor: 'pf-coral',
      tags:    ['Seasonal light', 'Elderly', 'Circadian'],
    },
    {
      id:      'proj-ries-lac',
      status:  'active',
      agency:  'ANID · REDES',
      code:    'RIES-LAC',
      title:   'Red Interuniversitaria de Envejecimiento Saludable para América Latina y el Caribe — participación NIM-ACh',
      pi:      'Dr. Cristian Núñez Espinosa',
      period:  '2024–2026',
      amount:  'Red',
      type:    'Red ANID',
      progress: 60,
      barColor: 'pf-purple',
      tags:    ['Aging', 'LATAM', 'Network'],
    },
  ],

  /* ─── News ─── */
  news: [
    { date:'Dic 2025', hot:true,  text:'Matías Castillo-Aguilar lanza app web para análisis de VFC con bandas Polar H10.',                                             tag:'Herramienta open-source', link:'https://deft-torte-3c1940.netlify.app/' },
    { date:'Jun 2025', hot:true,  text:'Primer Seminario "Mentes del Fin del Mundo" — con estudiantes de toda la Región de Magallanes.',                               tag:'Divulgación' },
    { date:'Ene 2025', hot:true,  text:'Dr. Cristian Núñez adjudica FONDECYT Regular 2025.',                                                                          tag:'Financiamiento' },
    { date:'Nov 2024', hot:false, text:'Tiare Ibinarriaga aceptada en programa de Doctorado — UDD 2025.',                                                             tag:'Formación' },
    { date:'Jun 2024', hot:false, text:'Inicio de mediciones en nadadores de aguas gélidas de Magallanes.',                                                           tag:'Terreno' },
    { date:'May 2024', hot:false, text:'Vínculo con Universidad de Salvador de Bahía en el marco de MEDIANTAR.',                                                      tag:'Internacional' },
    { date:'Ene 2024', hot:false, text:'Colaboraciones con RIES-LAC — Red Interuniversitaria de Envejecimiento Saludable.',                                           tag:'Colaboración' },
    { date:'May 2023', hot:false, text:'Inicio de proyecto FONDECYT Iniciación con evaluación de deportistas y mindfulness en personas mayores.',                     tag:'Investigación' },
  ],

  /* ─── Research lines ─── */
  research: [
    {
      id:    'neuromodulation',
      icon:  '🧠',
      color: 'rc-blue',
      ic:    'ic-blue',
      title: 'Neuromodulación y variabilidad de frecuencia cardíaca',
      desc:  'Evaluación de la VFC como marcador del control autonómico bajo diversas condiciones fisiológicas, psicológicas y ambientales.',
      tags:  ['HRV', 'Autonomic NS', 'Polar H10', 'Wearables'],
    },
    {
      id:    'extreme-environments',
      icon:  '🏔️',
      color: 'rc-coral',
      ic:    'ic-coral',
      title: 'Ambientes extremos y estrés fisiológico',
      desc:  'Respuesta del eje cerebro-corazón al frío extremo, altitud, inmersión en aguas gélidas y ejercicio intenso en la Patagonia.',
      tags:  ['Cold exposure', 'Exercise', 'Patagonia', 'Open water'],
    },
    {
      id:    'aging-mindfulness',
      icon:  '🌿',
      color: 'rc-teal',
      ic:    'ic-teal',
      title: 'Mindfulness y envejecimiento saludable',
      desc:  'Efecto de intervenciones de mindfulness sobre el deterioro cognitivo y la regulación autonómica en adultos mayores de Magallanes.',
      tags:  ['Aging', 'Mindfulness', 'Cognition', 'RIES-LAC'],
    },
  ],
  
  /* ─── Paradigm ─── */
  paradigm: {
    quote: 'La resiliencia no es un rasgo, es un proceso dinámico de auto-organización (autopoiesis) mediante el cual el organismo gestiona recursos fisiológicos para preservar la funcionalidad y la autonomía regulatoria en escenarios de perturbación, y esa gestión se aprende.',
    pillars: [
      {
        id:       'dynamism',
        num:      '01',
        icon:     '↺',
        color:    'blue',
        label:    'Dinamismo',
        question: '¿Cómo se mide la adaptación?',
        desc:     'Lo relevante no es solo el nivel promedio, sino la capacidad de reorganizarse: flexibilidad, estabilidad, recuperación y acoplamientos entre sistemas.',
        tags:     ['Flexibilidad', 'Estabilidad', 'Recuperación', 'Acoplamientos'],
      },
      {
        id:       'resources',
        num:      '02',
        icon:     '⚡',
        color:    'coral',
        label:    'Gestión de recursos',
        question: '¿Qué distribuye el organismo?',
        desc:     'La adaptación depende de cómo el cuerpo distribuye y recupera recursos en el eje autonómico–inmune–cerebro.',
        tags:     ['Autonómico', 'Inmune', 'Cerebro', 'Distribución'],
      },
      {
        id:       'learning',
        num:      '03',
        icon:     '◉',
        color:    'teal',
        label:    'Aprendizaje corporal',
        question: '¿Cómo se consolida la resiliencia?',
        desc:     'Las estrategias se consolidan por repetición y dejan huellas fisiológicas medibles: hábitos, entrenamiento, regulación emocional, sueño, exposición al frío.',
        tags:     ['Hábitos', 'Entrenamiento', 'Sueño', 'Huellas fisiológicas'],
      },
    ],
  },

  /* ─── Collaborators ─── */
  collaborators: [
    { name:'MEDIANTAR',        url:'#' },
    { name:'RIES-LAC',         url:'#' },
    { name:'CIES',             url:'#' },
    { name:'HABITAT',          url:'#' },
    { name:'U. Salvador Bahía',url:'#' },
    { name:'FONDECYT',         url:'#' },
  ],
  
  globePoints: [
    { lat:-53.16, lon:-70.91, label:'Punta Arenas — NIM-ACh', color:'#e87040', r:1.0, home:true  },
    { lat:-33.45, lon:-70.66, label:'Santiago',                color:'#7fb3e8', r:0.6, home:false },
    { lat:-12.97, lon:-38.50, label:'Salvador de Bahía · MEDIANTAR', color:'#7fb3e8', r:0.7, home:false },
    { lat: 19.43, lon:-99.13, label:'Ciudad de México · RIES-LAC',   color:'#7fb3e8', r:0.6, home:false },
    { lat: 40.42, lon: -3.70, label:'Madrid · ERASMUS+',       color:'#1db884', r:0.7, home:false },
    { lat: 48.86, lon:  2.35, label:'París',                   color:'#7fb3e8', r:0.5, home:false },
    { lat: 41.90, lon: 12.49, label:'Roma · MEDIANTAR',        color:'#7fb3e8', r:0.6, home:false },
    { lat:-34.90, lon:-56.17, label:'Montevideo · RIES-LAC',   color:'#b07fd4', r:0.5, home:false },
  ],

  /* ─── Gallery items ─── */
  gallery: [
    { id:'g1', bg:'gi-1', span:true,  title:'Mediciones de VFC en laboratorio',           sub:'CADI-UMAG · 2024' },
    { id:'g2', bg:'gi-2', span:false, title:'Terreno en Patagonia',                       sub:'Nadadores aguas gélidas · Jun 2024' },
    { id:'g3', bg:'gi-3', span:false, title:'Seminario Mentes del Fin del Mundo',         sub:'Punta Arenas · Jun 2025' },
    { id:'g4', bg:'gi-4', span:false, title:'Colaboración MEDIANTAR',                     sub:'Brasil · 2024' },
    { id:'g5', bg:'gi-5', span:false, title:'CIES Jornadas Talca',                        sub:'Congreso · Sep 2023' },
    { id:'g6', bg:'gi-6', span:false, title:'Mediciones mindfulness adultos mayores',     sub:'UMAG · 2023' },
  ],
  
  /* ─── Tools ─── */
  tools: [
    {
      id:       'hrv-analyzer',
      icon:     '💓',
      status:   'active',
      version:  'v2.0',
      title:    'HRV Analyzer — Polar H10 Web App',
      desc:     'Aplicación web para análisis de variabilidad de frecuencia cardíaca en tiempo real usando bandas Polar H10 vía Web Bluetooth. Sin instalación, sin cuenta, sin costo.',
      features: [
        'Métricas en dominio tiempo (SDNN, RMSSD, pNN50)',
        'Análisis frecuencial (LF, HF, LF/HF)',
        'Poincaré plot en tiempo real',
        'Exportación CSV / JSON',
        'Compatible con Polar H10 y H9',
      ],
      tags:     ['Web Bluetooth', 'JavaScript', 'HRV', 'Polar H10', 'Open Source'],
      author:   'matias-castillo',
      url:      'https://deft-torte-3c1940.netlify.app/',
      github:   '#',
      docs:     '#',
    },
    {
      id:       'nim-stats',
      icon:     '📊',
      status:   'dev',
      version:  null,
      title:    'NIM-Stats — Pipeline estadístico HRV',
      desc:     'CLI en Python para procesamiento batch de archivos RR. Genera reportes automáticos en PDF con visualizaciones estandarizadas y estadísticas descriptivas.',
      features: [
        'Procesamiento batch de archivos .rr y .csv',
        'Reporte PDF automatizado',
        'Gráficos Poincaré y frecuencial',
        'Compatible con Polar, Garmin y Kubios',
      ],
      tags:     ['Python', 'CLI', 'Batch', 'PDF'],
      author:   'matias-castillo',
      url:      null,
      github:   '#',
      docs:     null,
    },
    {
      id:       'nim-annotator',
      icon:     '🗂️',
      status:   'planned',
      version:  null,
      title:    'NIM-Annotator — Etiquetado de artefactos',
      desc:     'Interfaz visual para revisar y limpiar series RR, con detección automática de ectópicos y exportación de segmentos anotados con metadatos.',
      features: [
        'Detección automática de latidos ectópicos',
        'Edición manual de artefactos',
        'Exportación de segmentos con metadatos',
        'Integración con NIM-Stats',
      ],
      tags:     ['React', 'Annotation', 'QC', 'TypeScript'],
      author:   null,
      url:      null,
      github:   null,
      docs:     null,
    },
  ],

  /* ─── News / Timeline ─── */
  news: [
    {
      date: 'Dic 2025',
      html: 'Matías Castillo-Aguilar lanza <a href="https://deft-torte-3c1940.netlify.app/" style="color:var(--c-coral)">app web</a> para análisis de VFC con bandas Polar H10.',
      tag:  'Herramienta open-source',
      hot:  true,
    },
    {
      date: 'Jun 2025',
      html: 'Primer Seminario "Mentes del Fin del Mundo" — gran convocatoria regional en Punta Arenas.',
      tag:  'Divulgación',
      hot:  true,
    },
    {
      date: 'Ene 2025',
      html: 'Dr. Núñez inicia trabajo de campo del FONDECYT Regular con nadadores de aguas gélidas de Magallanes.',
      tag:  'Investigación',
      hot:  true,
    },
    {
      date: 'Oct 2024',
      html: 'NIM-ACh presentó 3 trabajos en el congreso CIES 2024 en Talca. Dos menciones de honor.',
      tag:  'Congreso',
      hot:  false,
    },
    {
      date: 'Ago 2024',
      html: 'Inicio oficial de colaboración MEDIANTAR (ERASMUS+) con universidades de Brasil, España e Italia.',
      tag:  'Colaboración internacional',
      hot:  false,
    },
    {
      date: 'Mar 2024',
      html: 'Publicación aceptada en <em>Frontiers in Aging Neuroscience</em>: efectos del mindfulness en adultos mayores.',
      tag:  'Publicación',
      hot:  false,
    },
    {
      date: 'Dic 2023',
      html: 'NIM-ACh se incorpora a la Red RIES-LAC de envejecimiento saludable en América Latina.',
      tag:  'Red científica',
      hot:  false,
    },
  ],
};

window.NIMACH_DATA = NIMACH_DATA;
