/**
 * NIM-ACh — Site Data
 * Centralised data store. Edit here to update all sections.
 * In a production build, replace with API calls to a CMS.
 */

const NIMACH_DATA = {
  
  // ADD before  people: [
  people_categories: [
    { key: 'pi',            label: 'Investigación Principal'   },
    { key: 'researcher',    label: 'Investigadores'            },
    { key: 'undergrad',     label: 'Estudiante de Pregrado'    },
    { key: 'posgrad',       label: 'Estudiante de Posgrado'    },
    { key: 'clinician',     label: 'Colaboradores Clínicos'    },
    { key: 'collaborator',  label: 'Colaboradores Externos'    },
    { key: 'staff',         label: 'Gestión y Apoyo'           },
  ],

  /* ─── People ─── */
  people: [
    {
      id:            'cristian-nunez',
      active:        true,
      initials:      'CN',
      name:          'Cristian Núñez Espinosa',
      role:          'Investigador Principal · CADI-UMAG',
      role_category: ['pi'],
      avatar:        'av1',
      photo:         'assets/images/team/cris-nunez.jpg', 
      featured_home: true,
      ringColor:     '#3b7abf',
      bio:           'Doctor en Fisiología. Especialista en neurofisiología y regulación autonómica cardíaca. Lidera el laboratorio NIM-ACh y proyectos FONDECYT sobre el eje cerebro-corazón en contextos extremos patagónicos. Académico de la Escuela de Medicina de la UMAG.',
      chips:         ['FONDECYT', 'Neurofisiología', 'HRV'],
      links:         { researchgate: '#', orcid: '#', scholar: '#' },
    },
    {
      id:            'matias-castillo',
      active:        true,
      initials:      'MCA',
      name:          'Matías Castillo-Aguilar',
      role:          'Investigador',
      role_category: ['researcher', 'staff'],
      avatar:        'av2',
      photo:         'assets/images/team/matias-castillo.jpeg', 
      featured_home: true,
      ringColor:     '#e87040',
      bio:           'Kinesiólogo. Investigador de procesos autonomicos cardíacos no estacionarios en respuesta al ejercicio. Desarrolla modelos estadísticos probabilisticos, mecanisticos y generativos para explicar dinámicas autonómicas en respuesta al ejercicio.',
      chips:         ['HRV', 'App Dev', 'Analítica'],
      links:         { github: '#', orcid: '#' },
    },
    {
      id:            'javiera-gonzalez',
      active:        true,
      initials:      'JG',
      name:          'Javiera Gonzalez Ojeda',
      role:          'Kinesiologa · Coordinadora de proyectos de investigación.',
      role_category: ["staff"],
      featured_home: true,
      photo:         'assets/images/team/javiera-gonzalez.jpg', 
      bio:           'Encargada de la planificación, ejecución y seguimiento de proyectos científicos. Coordina equipos de trabajo y gestiona procesos asociados a investigación en salud, asegurando el cumplimiento de objetivos, tiempos y estándares de calidad.',
      chips:         ['Gestion'],
      links:         { researchgate: '#' },
    },
    {
      id:            'diego-mabe',
      active:        true,
      initials:      'DM',
      name:          'Diego Mabe',
      role:          'Investigador',
      role_category: ["researcher"],
      featured_home: true,
      photo:         'assets/images/team/diego-mabe.jpeg', 
      bio:           'Kinesiólogo. Estudia aspectos funcionales, clinicos y celulares de la fragilidad y sarcopenia.',
      chips:         ['Fragilidad', 'Kinesiología', 'Envejecimiento'],
      links:         { researchgate: 'https://www.researchgate.net/profile/Diego-Mabe-Castro-2/research', orcid: 'https://orcid.org/0000-0002-6663-2153', scholar: 'https://scholar.google.com/citations?user=q3RS7sUAAAAJ&hl=en' },
    },
    {
      id:            'atenea-uribe',
      active:        true,
      initials:      'AU',
      name:          'Atenea Uribe-Ojeda',
      role:          'Investigadora Posdoctoral',
      role_category: ["researcher", "staff"],
      featured_home: true,
      photo:         'assets/images/team/atenea-uribe.jpg', 
      bio:           'Doctora en Fisiología Celular y Molecular. Encargada de la sección de experimentación molecular del grupo. Estudia mecanismos celulares y metabólicos del climaterio en la cognición y procesos neuroplásticos en mujeres.',
      chips:         ['Climaterio', 'Bioquímica', 'Mecanismos moleculares'],
      links:         { researchgate: 'https://www.researchgate.net/profile/Atenea-Uribe-Ojeda', orcid: "https://orcid.org/0000-0001-9846-8602"},
    },
    {
      id:            'cristobal-canales',
      active:        true,
      initials:      'CC',
      name:          'Cristobal Canales',
      role:          'Investigador',
      role_category: ["researcher","staff"],
      featured_home: true,
      avatar:        'av5',
      ringColor:     '#3baabf',
      photo:         'assets/images/team/cristobal-canales.jpg', 
      bio:           'Bioquímico especialista en mediciones moleculares, procedimientos de laboratorio y gestión de inventario de laboratorio.',
      chips:         ['Laboratorio', 'Bioquímica'],
      links:         { researchgate: '#' },
    },
    {
      id:            'sergio-cares',
      active:        true,
      initials:      'SE',
      name:          'Sergio Cares',
      role:          'Investigador asociada',
      role_category: ['researcher'],
      photo:         'assets/images/team/sergio-cares.jpg', 
      featured_home: false,
      bio:           'Kinesiólogo clínico especialista en medicina del deporte.',
      chips:         ['Kinesiología', "Deporte"],
      links:         { researchgate: '#' },
    },
    {
      id:            'claudia-estrada',
      active:        true,
      initials:      'CE',
      name:          'Claudia Estrada',
      role:          'Investigador asociada',
      role_category: ['researcher'],
      avatar:        'av4',
      photo:         'assets/images/team/claudia-estrada.jpeg', 
      featured_home: false,
      ringColor:     '#d4903a',
      bio:           'Doctora en Psicología',
      chips:         ['Psicología'],
      links:         { researchgate: '#' },
    },
    {
      id:            'leyla-huirimilla',
      active:        true,
      initials:      'LV',
      name:          'Leyla Huirimilla',
      role:          'Investigadora asociada',
      role_category: ['posgrad', 'researcher'],
      avatar:        'av4',
      photo:         'assets/images/team/leyla-huirimilla.jpg', 
      featured_home: false,
      ringColor:     '#7b52d4',
      bio:           'Psicóloga clínica, Magíster en Psicobiología del Desarrollo. Estudiante de Doctorado',
      chips:         ['Envejecimiento', 'Mindfulness'],
      links:         { researchgate: '#' },
    },
    {
      id:            'jonathan-luhr',
      active:        true,
      initials:      'JL',
      name:          'Jonathan Lühr',
      role:          'Investigador asociado',
      role_category: ['posgrad', 'researcher'],
      avatar:        'av5',
      photo:         'assets/images/team/jonathan.jpg', 
      featured_home: false,
      ringColor:     '#d4903a',
      bio:           'Psicólogo Clínico. Estudiante de Doctorado, enfocado en estudiar trayectorias cognitivas y funcionales en mujeres durante el climaterio.',
      chips:         ['Psicología'],
      links:         { researchgate: '#' },
    },
    {
      id:            'ruby-mendez',
      active:        true,
      initials:      'RM',
      name:          'Ruby Méndez',
      role:          'Investigadora asociado',
      role_category: ['researcher'],
      photo:         'assets/images/team/ruby-mendez.jpg', 
      featured_home: false,
      bio:           'Profesora de Educación Física y Magíster en Psicobiología del Desarrollo Humano. Actualmente lleva los talleres de pilates para personas mayores.',
      chips:         ['Deporte'],
      links:         { researchgate: '#' },
    },
    {
      id:            'marcelo-andrade',
      active:        true,
      initials:      'MA',
      name:          'Marcelo Andrade',
      role:          'Nutricionista e Investigador',
      role_category: ["clinician"],
      photo:         'assets/images/team/marcelo-andrade.jpeg', 
      featured_home: false,
      bio:           'Nutricionista clinico enfocado en perfiles antropométricos y su relación con atributos funcionales en deportistas de alto rendimiento.',
      chips:         ['Nutrición', 'Deportistas'],
      links:         { researchgate: '#' },
    },
    {
      id:            'valeska-oyarzo',
      active:        true,
      initials:      'VV',
      name:          'Valeska Oyarzo',
      role:          'Fonoaudióloga',
      role_category: ["clinician"],
      photo:         'assets/images/team/valeska-oyarzo.jpg', 
      featured_home: false,
      bio:           'Fonoaudióloga clinica.',
      chips:         ['Fonoaudiología'],
    },
    {
      id:            'valeska-villegas',
      active:        true,
      initials:      'VV',
      name:          'Valeska Villegas',
      role:          'Kinesióloga',
      role_category: ["clinician"],
      photo:         'assets/images/team/valeska-villegas.jpg', 
      featured_home: false,
      bio:           'Kinesióloga clinica.',
      chips:         ['Kinesiología'],
    },
    {
      id:            'matias-mabe',
      active:        true,
      initials:      'DM',
      name:          'Matías Mabe',
      role:          'Interno de Medicina',
      role_category: ["undergrad", "researcher"],
      featured_home: false,
      avatar:        'av5',
      photo:         'assets/images/team/matias-mabe.jpeg', 
      ringColor:     '#3baabf',
      bio:           'Estudiante de Medicina e investigador. Estudia aspectos funcionales, clinicos y celulares de la fragilidad y sarcopenia.',
      chips:         ['Fragilidad', 'Medicina'],
      links:         { researchgate: '#' },
    },
    {
      id:            'josefa-lillo',
      active:        true,
      initials:      'JL',
      name:          'Josefa Lillo',
      role:          'Estudiante de Medicina',
      role_category: ["undergrad", "researcher"],
      featured_home: false,
      avatar:        'av5',
      photo:         'assets/images/team/josefa-lillo.jpeg', 
      ringColor:     '#3baabf',
      bio:           'Estudiante de Medicina e investigadora. Investiga aspectos relacionados con la termorregulación y modulación autonómica cardíaca de deportistas en climas extremos fríos',
      chips:         ['Deportistas', 'Medicina'],
      links:         { researchgate: '#' },
    },
  ],

  /* ─── Publications ─── */
  publications: [],
  
  /* ─── Alumni ─── */
  alumni: [
    {
      id:        'katherine-harris',
      initials:  'KH',
      name:      'Katherine Harris',
      role:      'Kinesióloga',
      period:    '2019-2022',
      avatar:    'av3',   
      photo:     'assets/images/team/katherine-harris.jpeg', 
      ringColor: '#7b52d4',
      chips:     ['Biomecánica', 'Traumatología'],
      links:     null,
      currentPosition: null,
    },
    {
      id:            'tiare-ibinarriaga',
      initials:      'TI',
      name:          'Tiare Ibinarriaga',
      role:          'Investigadora doctoral · UDD 2025',
      avatar:        'av3',
      period:        '2020-2022',
      photo:         'assets/images/team/tiare-ibinarriaga.jpg', 
      ringColor:     '#1db884',
      chips:         ['PhD', 'Psicopatología'],
      links:         null,
      currentPosition: 'Universidad del Desarrollo',
    },
    {
      id:        'roberto-herrera',
      initials:  'RH',
      name:      'Roberto Herrera',
      role:      'Psicólogo Clínico',
      period:    '2022–2023',
      photo:     'assets/images/team/roberto-herrera.jpeg', 
      chips:     ['Psicología'],
      links:     null,
      currentPosition: null,
    },
    {
      id:        'matias-riquelme',
      initials:  'MR',
      name:      'Matías Riquelme',
      role:      'Médico Cirujano',
      period:    '2019–2022',
      photo:     'assets/images/team/matias-riquelme.jpeg', 
      chips:     ['Medicina'],
      links:     null,
      currentPosition: null,
    },
    {
      id:        'caren-alvarado',
      initials:  'CA',
      name:      'Caren Alvarado',
      role:      'Médica Cirujana',
      period:    '2019–2023',
      photo:     'assets/images/team/caren-alvarado.jpg', 
      chips:     ['Medicina'],
      links:     null,
      currentPosition: null,
    },
  ],

  /* ─── NIMAChinos (mascotas del equipo) ─── */
  pets: [
    {
      id:       'pet-vader',
      name:     'Vader',
      species:  'Gato',
      breed:    'Mestizo rescatado',
      photo:    'assets/images/pets/vader.jpeg',
      owner:    'matias-castillo',
      bio:      'Supervisor técnico del desarrollo de aplicaciones. Verifica cada commit con su mirada escéptica y ocasionalmente camina sobre el teclado para contribuir.',
      joined:   '2026',
    },
    {
      id:       'pet-limon',
      name:     'Limón',
      species:  'Gato',
      breed:    'Mestizo pelo corto',
      photo:    'assets/images/pets/limoncito-javi.jpeg',
      owner:    'javiera-gonzalez',
      bio:      'Asistente de apoyo y clima laboral. Rescatado y profundamente agradecido, se especializa en acompañamiento emocional y soporte continuo en jornadas de trabajo desde el hogar',
      joined:   '2024',
    },
    {
      id:       'pet-coco',
      name:     'Coco',
      species:  'Gato',
      breed:    'Mestizo pelo corto',
      photo:    'assets/images/pets/coco-javiera.jpeg',
      owner:    'javiera-gonzalez',
      bio:      'Coordinador senior de equipo y bienestar felino. Con más de 10 años de experiencia, supervisa de forma independiente el funcionamiento general, manteniéndose siempre atento a cada integrante del equipo.',
      joined:   '2016',
    },
    {
      id:       'pet-mango',
      name:     'Mango',
      species:  'Gato',
      breed:    'Mestizo pelo semilargo',
      photo:    'assets/images/pets/mango.jpeg',
      owner:    'javiera-gonzalez',
      bio:      'Practicante de innovación y caos creativo. Incorporado recientemente de forma inesperada, aporta energía, curiosidad y disrupción a los procesos.',
      joined:   '2026',
    },
    {
      id:       'pet-miko',
      name:     'Miko',
      species:  'Perro',
      breed:    'Mestizo rescatado',
      photo:    'assets/images/pets/miko-diego.jpeg',
      owner:    'diego-mabe',
      bio:      'Coordinador de actividad física y dinamización del entorno. Destaca por su alta demanda energética y compromiso sostenido con el movimiento, promoviendo pausas activas estructuradas y sesiones de ejercicio diario',
      joined:   '2020',
    },
  ],

  /* ─── Projects ─── */
  projects: [
    {
      id:      'proj-fondecyt-regular-2025',
      status:  'active',
      agency:  'ANID · FONDECYT Regular',
      code:    'Nº 1XXXXXX',
      title:   'Regulación autonómica cardíaca en condiciones de frío extremo: estudio en nadadores de aguas gélidas de Magallanes',
      pi:      'Dr. Cristian Núñez Espinosa',
      period:  '2025–2028',
      amount:  '$105M CLP',
      type:    'Regular',
      progress: 25,
      barColor: 'pf-teal',
      tags:    ['HRV', 'Patagonia', 'Autonomic'],
    },
    {
      id:      'proj-mediantar-2024',
      status:  'active',
      agency:  'UE · ERASMUS+',
      code:    'MEDIANTAR 2024–2028',
      title:   'Mediterranean and Antarctic Research Network: ambientes extremos y ejercicio físico en contextos internacionales',
      pi:      'Colaborador: Dr. Cristian Núñez Espinosa',
      period:  '2024–2028',
      amount:  'Internacional',
      type:    'Internacional',
      progress: 40,
      barColor: 'pf-blue',
      tags:    ['International', 'Brazil', 'Exercise', 'Extreme env.'],
    },
    {
      id:      'proj-fondecyt-ini-2022',
      status:  'complete',
      agency:  'ANID · FONDECYT Iniciación',
      code:    'Nº 11XXXXX',
      title:   'Efectos de la luz estacional en la regulación autonómica de personas mayores residentes en la Región de Magallanes',
      pi:      'Dr. Cristian Núñez Espinosa',
      period:  '2022–2024',
      amount:  '$55M CLP',
      type:    'Iniciación',
      progress: 100,
      barColor: 'pf-coral',
      tags:    ['Seasonal light', 'Elderly', 'Circadian'],
    },
    {
      id:      'proj-ries-lac',
      status:  'active',
      agency:  'ANID · REDES',
      code:    'RIES-LAC',
      title:   'Red Interuniversitaria de Envejecimiento Saludable para América Latina y el Caribe — participación NIM-ACh',
      pi:      'Dr. Cristian Núñez Espinosa',
      period:  '2024–2026',
      amount:  'Red',
      type:    'Red ANID',
      progress: 60,
      barColor: 'pf-purple',
      tags:    ['Aging', 'LATAM', 'Network'],
    },
  ],

  /* ─── News ─── */
  news: [
    { date:'Dic 2025', hot:true,  text:'Matías Castillo-Aguilar lanza app web para análisis de VFC con bandas Polar H10.',                                             tag:'Herramienta open-source', link:'https://deft-torte-3c1940.netlify.app/' },
    { date:'Jun 2025', hot:true,  text:'Primer Seminario "Mentes del Fin del Mundo" — con estudiantes de toda la Región de Magallanes.',                               tag:'Divulgación' },
    { date:'Ene 2025', hot:true,  text:'Dr. Cristian Núñez adjudica FONDECYT Regular 2025.',                                                                          tag:'Financiamiento' },
    { date:'Nov 2024', hot:false, text:'Tiare Ibinarriaga aceptada en programa de Doctorado — UDD 2025.',                                                             tag:'Formación' },
    { date:'Jun 2024', hot:false, text:'Inicio de mediciones en nadadores de aguas gélidas de Magallanes.',                                                           tag:'Terreno' },
    { date:'May 2024', hot:false, text:'Vínculo con Universidad de Salvador de Bahía en el marco de MEDIANTAR.',                                                      tag:'Internacional' },
    { date:'Ene 2024', hot:false, text:'Colaboraciones con RIES-LAC — Red Interuniversitaria de Envejecimiento Saludable.',                                           tag:'Colaboración' },
    { date:'May 2023', hot:false, text:'Inicio de proyecto FONDECYT Iniciación con evaluación de deportistas y mindfulness en personas mayores.',                     tag:'Investigación' },
  ],

  /* ─── Research lines ─── */
  research: [
    {
      id:    'neuromodulation',
      icon:  '🧠',
      color: 'rc-blue',
      ic:    'ic-blue',
      title: 'Neuromodulación y variabilidad de frecuencia cardíaca',
      desc:  'Evaluación de la VFC como marcador del control autonómico bajo diversas condiciones fisiológicas, psicológicas y ambientales.',
      tags:  ['HRV', 'Autonomic NS', 'Polar H10', 'Wearables'],
    },
    {
      id:    'extreme-environments',
      icon:  '🏔️',
      color: 'rc-coral',
      ic:    'ic-coral',
      title: 'Ambientes extremos y estrés fisiológico',
      desc:  'Respuesta del eje cerebro-corazón al frío extremo, altitud, inmersión en aguas gélidas y ejercicio intenso en la Patagonia.',
      tags:  ['Cold exposure', 'Exercise', 'Patagonia', 'Open water'],
    },
    {
      id:    'aging-mindfulness',
      icon:  '🌿',
      color: 'rc-teal',
      ic:    'ic-teal',
      title: 'Mindfulness y envejecimiento saludable',
      desc:  'Efecto de intervenciones de mindfulness sobre el deterioro cognitivo y la regulación autonómica en adultos mayores de Magallanes.',
      tags:  ['Aging', 'Mindfulness', 'Cognition', 'RIES-LAC'],
    },
  ],
  
  /* ─── Paradigm ─── */
  paradigm: {
    quote: 'La resiliencia no es un rasgo, es un proceso dinámico de auto-organización (autopoiesis) mediante el cual el organismo gestiona recursos fisiológicos para preservar la funcionalidad y la autonomía regulatoria en escenarios de perturbación, y esa gestión se aprende.',
    pillars: [
      {
        id:       'dynamism',
        num:      '01',
        icon:     '↺',
        color:    'blue',
        label:    'Dinamismo',
        question: '¿Cómo se mide la adaptación?',
        desc:     'Lo relevante no es solo el nivel promedio, sino la capacidad de reorganizarse: flexibilidad, estabilidad, recuperación y acoplamientos entre sistemas.',
        tags:     ['Flexibilidad', 'Estabilidad', 'Recuperación', 'Acoplamientos'],
      },
      {
        id:       'resources',
        num:      '02',
        icon:     '⚡',
        color:    'coral',
        label:    'Gestión de recursos',
        question: '¿Qué distribuye el organismo?',
        desc:     'La adaptación depende de cómo el cuerpo distribuye y recupera recursos en el eje autonómico–inmune–cerebro.',
        tags:     ['Autonómico', 'Inmune', 'Cerebro', 'Distribución'],
      },
      {
        id:       'learning',
        num:      '03',
        icon:     '◉',
        color:    'teal',
        label:    'Aprendizaje corporal',
        question: '¿Cómo se consolida la resiliencia?',
        desc:     'Las estrategias se consolidan por repetición y dejan huellas fisiológicas medibles: hábitos, entrenamiento, regulación emocional, sueño, exposición al frío.',
        tags:     ['Hábitos', 'Entrenamiento', 'Sueño', 'Huellas fisiológicas'],
      },
    ],
  },

  /* ─── Collaborators ─── */
  collaborators: [
    { name:'MEDIANTAR',        url:'#' },
    { name:'RIES-LAC',         url:'#' },
    { name:'CIES',             url:'#' },
    { name:'HABITAT',          url:'#' },
    { name:'U. Salvador Bahía',url:'#' },
    { name:'FONDECYT',         url:'#' },
  ],
  
  globePoints: [
    { lat:-53.16, lon:-70.91, label:'Punta Arenas — NIM-ACh', color:'#e87040', r:1.0, home:true  },
    { lat:-33.45, lon:-70.66, label:'Santiago',                color:'#7fb3e8', r:0.6, home:false },
    { lat:-12.97, lon:-38.50, label:'Salvador de Bahía · MEDIANTAR', color:'#7fb3e8', r:0.7, home:false },
    { lat: 19.43, lon:-99.13, label:'Ciudad de México · RIES-LAC',   color:'#7fb3e8', r:0.6, home:false },
    { lat: 40.42, lon: -3.70, label:'Madrid · ERASMUS+',       color:'#1db884', r:0.7, home:false },
    { lat: 48.86, lon:  2.35, label:'París',                   color:'#7fb3e8', r:0.5, home:false },
    { lat: 41.90, lon: 12.49, label:'Roma · MEDIANTAR',        color:'#7fb3e8', r:0.6, home:false },
    { lat:-34.90, lon:-56.17, label:'Montevideo · RIES-LAC',   color:'#b07fd4', r:0.5, home:false },
  ],

  /* ─── Gallery items ─── */
  gallery: [
    { id:'g1', bg:'gi-1', span:true,  title:'Mediciones de VFC en laboratorio',           sub:'CADI-UMAG · 2024' },
    { id:'g2', bg:'gi-2', span:false, title:'Terreno en Patagonia',                       sub:'Nadadores aguas gélidas · Jun 2024' },
    { id:'g3', bg:'gi-3', span:false, title:'Seminario Mentes del Fin del Mundo',         sub:'Punta Arenas · Jun 2025' },
    { id:'g4', bg:'gi-4', span:false, title:'Colaboración MEDIANTAR',                     sub:'Brasil · 2024' },
    { id:'g5', bg:'gi-5', span:false, title:'CIES Jornadas Talca',                        sub:'Congreso · Sep 2023' },
    { id:'g6', bg:'gi-6', span:false, title:'Mediciones mindfulness adultos mayores',     sub:'UMAG · 2023' },
  ],
  
  /* ─── Tools ─── */
  tools: [
    {
      id:       'hrv-analyzer',
      icon:     '💓',
      status:   'active',
      featured_home: true,
      featured_page: true,
      version:  'v2.0',
      title:    'HRV Recorder — Polar H10 Web App',
      desc:     'Aplicación web para análisis de variabilidad de frecuencia cardíaca en tiempo real usando bandas Polar H10 vía Web Bluetooth. Sin instalación, sin cuenta, sin costo.',
      features: [
        'Métricas en dominio tiempo (SDNN, RMSSD, pNN50)',
        'Análisis frecuencial (LF, HF, LF/HF)',
        'Poincaré plot en tiempo real',
        'Exportación CSV / JSON',
        'Compatible con Polar H10 y H9',
      ],
      tags:     ['Web Bluetooth', 'JavaScript', 'HRV', 'Polar H10', 'Open Source'],
      author:   'matias-castillo',
      url:      'https://deft-torte-3c1940.netlify.app/',
      github:   '#',
      docs:     '#',
    },
    {
      id:       'hrv-studio',
      icon:     '📊',
      status:   'dev',
      featured_home: false,
      featured_page: false,
      version:  'v1.0',
      title:    'HRV Studio — Pipeline de Análisis de HRV',
      desc:     'Web app para procesamiento batch de archivos RR. Genera reportes automáticos en PDF o HTML con visualizaciones estandarizadas y estadísticas descriptivas.',
      features: [
        'Procesamiento batch de archivos .rr y .csv',
        'Reporte PDF o HTLM automatizado',
        'Gráficos Poincaré y frecuencial',
        'Compatible con Polar, Garmin y Kubios',
      ],
      tags:     ['HRV', 'Análisis', 'Datos', 'Batch'],
      author:   'matias-castillo',
      url:      '#',
      github:   '#',
      docs:     '#',
    },
    {
      id:       'research-os',
      icon:     '🗂️',
      status:   'active',
      featured_home: false,
      featured_page: true,
      version:  'v1.0',
      title:    'ResearchOS — Workflow Científico local-first',
      desc:     'Herramienta de productividad científica local-first. Sin backend, sin telemetría — tus datos nunca salen de tu navegador. Diseñada para investigadores que gestionan proyectos, docencia, fondos y colaboraciones en paralelo.',
      features: [
        'Dashboard: Estadísticas, actividad reciente y accesos rápidos a Focus Feed, revisión de ideas y elementos huérfanos.',
        'Kanban Board: Gestiona el estado de tus proyectos arrastrando tarjetas entre columnas personalizables. Soporta límites WIP.',
        'Proyectos: Listado filtrable por tipo, prioridad y columna. Guarda filtros como vistas con nombre para acceso rápido.',
        'Project Hub: Abre el Hub desde cualquier proyecto para ver en una sola página: ideas, submissions, reuniones, referencias y snippets vinculados.',
        'Focus Feed: Qué hacer ahora según deadlines, acciones pendientes e ideas sin revisar.',
        'Submissions: Seguimiento de papers, grants y ponencias a través de su ciclo: preparación → enviado → revisión → aceptado/rechazado.',
        'Reuniones: Registra reuniones con acuerdos y próximos pasos. Las acciones pendientes aparecen en el Focus Feed.',
        'Referencias: Gestiona fuentes bibliográficas vinculadas a proyectos. Exporta a .bib con un clic.',
        'Ideas Inbox: Captura rápida de ideas. Usa la Revisión rápida (teclado) para procesar el inbox sin fricción.',
        'Snippets: Biblioteca de código por lenguaje y colección, vinculada a proyectos. Resaltado de sintaxis incluido.',
        'Agenda Semanal: Vista de solo lectura que agrega todos los deadlines, submissions y reuniones de los próximos 7 días.',
        'Timeline: Vista Gantt con zoom semana / mes / año. Filtra proyectos vencidos y colorea por prioridad o tipo.',
        'Huérfanos: Detecta ideas, snippets, referencias y reuniones sin proyecto asignado para mantener todo conectado.',
      ],
      tags:     ['React', 'Annotation', 'QC', 'TypeScript'],
      author:   'matias-castillo',
      url:      '#',
      github:   '#',
      docs:     '#',
    },
  ],

  /* ─── News / Timeline ─── */
  news: [
    {
      date: 'Dic 2025',
      html: 'Matías Castillo-Aguilar lanza <a href="https://deft-torte-3c1940.netlify.app/" style="color:var(--c-coral)">app web</a> para análisis de VFC con bandas Polar H10.',
      tag:  'Herramienta open-source',
      hot:  true,
    },
    {
      date: 'Jun 2025',
      html: 'Primer Seminario "Mentes del Fin del Mundo" — gran convocatoria regional en Punta Arenas.',
      tag:  'Divulgación',
      hot:  true,
    },
    {
      date: 'Ene 2025',
      html: 'Dr. Núñez inicia trabajo de campo del FONDECYT Regular con nadadores de aguas gélidas de Magallanes.',
      tag:  'Investigación',
      hot:  true,
    },
    {
      date: 'Oct 2024',
      html: 'NIM-ACh presentó 3 trabajos en el congreso CIES 2024 en Talca. Dos menciones de honor.',
      tag:  'Congreso',
      hot:  false,
    },
    {
      date: 'Ago 2024',
      html: 'Inicio oficial de colaboración MEDIANTAR (ERASMUS+) con universidades de Brasil, España e Italia.',
      tag:  'Colaboración internacional',
      hot:  false,
    },
    {
      date: 'Mar 2024',
      html: 'Publicación aceptada en <em>Frontiers in Aging Neuroscience</em>: efectos del mindfulness en adultos mayores.',
      tag:  'Publicación',
      hot:  false,
    },
    {
      date: 'Dic 2023',
      html: 'NIM-ACh se incorpora a la Red RIES-LAC de envejecimiento saludable en América Latina.',
      tag:  'Red científica',
      hot:  false,
    },
  ],
};

window.NIMACH_DATA = NIMACH_DATA;
